MAX_BRIGHTNESS_VALUE = 255
MIN_BRIGHTNESS_VALUE = 0

LEFT_BRIGHTNESS_VALUE = 96
RIGHT_BRIGHTNESS_VALUE = 160
CELL_HEIGHT = 16
IMAGE_HEIGHT = 128
IMAGE_LENGTH = 128
BORDER_PROCESSING_PARAMETER = 1
VALUE_OF_ONE = 1